project/Clase/urls.py
from django.urls import path
from . import views 

app_name = "Clase"


urlpatterns = [
    path("", views.home, name="home"),
    path("clasecategoria/create/", views.clasecategoria_create, name="clasecategoria_create"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("clase/", include("clase.urls")),
    path("region/", include("region.urls")),
    
]

project/core/urls.py
from django.urls import path
from . import views 


app_name = "Core"


urlpatterns = [
    path("", views.home,name="home"),
]

project/region/urls.py
from django.urls import path
from . import views 

app_name = "region"


urlpatterns = [
    path("", views.home, name="home"),
    path("regioncategoria/create/", views.regioncategoria_create, name="regioncategoria_create"),
]

project/Clase/models.py
from django.db import models

# Create your models here.
class Curso(models.Model):
    nombre = models.CharField(max_length=100)
      
    def __str__(self) -> str:
        return self.nombre

class Estudiante (models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.nombre

class Profesor (models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return self.nombre


class ClaseCategoria(models.Model):
    nombre = models.PositiveIntegerField(unique=True)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL, null=True, blank=True)
    estudiante = models.ManyToManyField(Estudiante)

    def __str__(self):
        return f"{self.nombre}, {self.curso}, {self.profesor}, {self.estudiante}"
    
    class Meta:
        verbose_name= "categoria de clase"
        verbose_name_plural = "categorias de clases"
    

project/core/models.py
from django.db import models

# Create your models here.

project/region/models.py
from django.db import models

# Create your models here.

class RegionCategoria(models.Model):
    """categoria de regio: urbana rural etc"""
    nombre = models.CharField(max_length=200, unique=True)
    zona = models.CharField(max_length=200, null=True, blank=True, verbose_name="zona")
    
    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name = "region del curso"
        verbose_name_plural= "regiones de curso"
        

project/Clase/forms.py
from django import forms        
from . import models

class ClaseCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ClaseCategoria    
        fields = "__all__"

project/region/forms.py
from django import forms

from . import models

#class Regioncategoriaform(forms.Form):
#  nombre = forms.CharField()
#  zona = forms.CharField()

class RegionCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.RegionCategoria
        fields = ["nombre","zona"]

project/Clase/views.py
from django.shortcuts import render, redirect
from . import forms, models

def home(request):
    consulta_clase = models.ClaseCategoria.objects.all()
    context = {"Clases": consulta_clase} 
    return render(request, "clase/index.html", context)


def clasecategoria_create(request):
    if request.method == "POST":    
         form = forms.ClaseCategoriaForm(request.POST)
         if form.is_valid():
              form.save()
              return redirect("clase:home")
    else:
         form = forms.ClaseCategoriaForm()
    return render(request, "clase/clasecategoria_create.html", context={"form": form})

project/core/views.py
from django.shortcuts import render

from . import models

def home(request):
    return render(request, "core/index.html")

project/region/views.py
from django.shortcuts import render, redirect

from . import forms, models

def home(request):
    consulta_region = models.RegionCategoria.objects.all()
    context = {"regiones": consulta_region} 
    return render(request, "region/index.html", context)


def regioncategoria_create(request):
    if request.method == "POST":
          form = forms.RegionCategoriaForm(request.POST)
          if form.is_valid():
               form.save() 
               return redirect("region:home")   
    else: 
        form= forms.RegionCategoriaForm()
    return render(request, "region/regioncategoria_create.html", context={"form": form})

project/Clase/templates/Clase/clasecategoria_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Categoria de comisiones
{% endblock titulo %}

{% block contenido %}
    
     <form action="" method="post">
        {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Guardar</button>
     </form>

{% endblock contenido %}

project/Clase/templates/Clase/index.html
{% extends 'core/base.html' %}
{% block titulo%}
     comisiones
{% endblock titulo %}

{% block contenido %}

    <div class="fs-3 pb-4 ">
         <a href="{% url 'clase:clasecategoria_create' %}">Crear Comision</a>
    </div>

    <ul>
        {% for clase in clases %} <li>{{ clase }}</li>{% endfor %}
    </ul>
    {% comment  %}
        <a href="{% url 'core:home' %}">ir a home</a>
    {% endcomment %}
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
                 app Facultad
            {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="   {% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include 'core/componentes/navbar.html' %}
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
              {% block titulo %}    
              {% endblock titulo %}
              
              {% block contenido %} 

              {% endblock contenido %}

        </div>
        <!-- Footer-->
        {% include 'core/componentes/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS--> 
        <script src=" {% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/componentes/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ texto }}</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Mas Info</a></div>
    </div>
    
</div>

project/core/templates/core/componentes/footer.html
<footer class="py-2 bg-dark fixed-bottom ">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Primer sitio Python</p></div>
</footer>

project/core/templates/core/componentes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Facultad Privada</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Core:home' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'Clase:home' %}">Clase</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'region:home' %}">Region</a></li>
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo%}
     Facultad privada
{% endblock titulo %}

{% block contenido %}
                <!-- Heading Row-->
                <div class="row gx-4 gx-lg-5 align-items-center my-5">
                    <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/img/note.webp' %}" alt="..." />
                </div>
                    <div class="col-lg-5">
                        <h1 class="font-weight-light">Curso</h1>
                        <p>Informacion sobre el curso businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                        <a class="btn btn-primary" href="https://wa.me/5493516013708" target="_blank">WhatsApp</a>
                    </div>
                </div>
                <!-- Call to Action-->
                <div class="card text-white bg-secondary my-5 py-4 text-center">
                    <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
                </div>
                <!-- Content Row-->
                <div class="row gx-4 gx-lg-5">
                    {% include 'core/componentes/card.html' with titulo="tarjeta 1" texto="promo1" %}
                    {% include 'core/componentes/card.html' with titulo="tarjeta 2" texto="promo2" %}
                    {% include 'core/componentes/card.html' with titulo="tarjeta 2" texto="promo2" %}
                    {% include 'core/componentes/card.html' with titulo="tarjeta 3" texto="promo3" %}
                </div>
{% endblock contenido%} 

project/region/templates/region/index.html
{% extends 'core/base.html' %}
{% block titulo%}
     Regiones
{% endblock titulo %}

{% block contenido %}
    <div class="fs-3 pb-4 ">
        <a href="{% url 'region:regioncategoria_create' %}">Crear categorias de regiones</a>
    </div>
    <ul>
        {% for region in regiones %} <li>{{ region }}</li>{% endfor %}
    </ul>
    {% comment  %}
        <a href="{% url 'core:home' %}">ir a home</a>
    {% endcomment %}
{% endblock contenido %}

project/region/templates/region/regioncategoria_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Categoria de region: regiones
{% endblock titulo %}

{% block contenido %}
    
     <form action="" method="post">
        {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Guardar</button>
     </form>

{% endblock contenido %}